"""add used fallback to analysis history

Revision ID: e9adad544fc0
Revises: 8d894f1e61f7
Create Date: 2026-09-12 23:49:51.013709

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9adad544fc0"
down_revision: str | Sequence[str] | None = "8d894f1e61f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_history",
        sa.Column(
            "used_fallback", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_history", "used_fallback")
    # ### end Alembic commands ###
